"""initial schema

Baseline migration: builds every table from the ORM models
(app/models.py), which is the schema source of truth. Subsequent changes are
their own autogenerated/hand-written revisions.

Revision ID: 0001
Revises:
Create Date: 2026-07-19
"""
from typing import Sequence, Union

from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from app.models import Base
    Base.metadata.create_all(op.get_bind())


def downgrade() -> None:
    from app.models import Base
    Base.metadata.drop_all(op.get_bind())
